- name: Vérifie si le module {{ mod_name }} est chargé
  shell: lsmod | grep -w {{ mod_name }}
  register: mod_loaded
  changed_when: false
  failed_when: false

- name: Vérifie la directive 'install' dans modprobe
  shell: modprobe --showconfig | grep -P '\binstall\s+{{ mod_name }}\s+(\/usr)?\/bin\/(true|false)\b'
  register: install_check
  failed_when: false
  changed_when: false

- name: Vérifie si le module est blacklisté
  shell: modprobe --showconfig | grep -P '\bblacklist\s+{{ mod_name }}\b'
  register: blacklist_check
  failed_when: false
  changed_when: false

- name: Définir un fait si l’audit échoue
  set_fact:
    mod_audit_failed: true
  when: >
    mod_loaded.rc == 0
    or install_check.rc != 0
    or blacklist_check.rc != 0

- name: Afficher le résultat de l’audit
  debug:
    msg: >-
      {% if not mod_audit_failed | default(false) %}
        ✅ Le module {{ mod_name }} est conforme : non chargé, non chargeable et blacklisté.
      {% else %}
        ❌ Le module {{ mod_name }} est chargé ou mal configuré.
      {% endif %}
