- name: Vérifie si {{ mod_name }} est dans la liste des CVEs et actif
  set_fact:
    warnings: "{{ warnings + [\" - ** WARNING: kernel module: '\" ~ mod_name ~ \"' has a CVE and is currently mounted! **\"] }}"
  when: mod_name in mounted_modules and mod_name in cve_modules

- name: Marque les modules montés mais non vulnérables
  set_fact:
    skipped_modules: "{{ skipped_modules + [\" - Kernel module: '\" ~ mod_name ~ \"' is currently mounted - do NOT unload or disable\"] }}"
  when: mod_name in mounted_modules and mod_name not in cve_modules

- name: Vérifie s’il manque un 'blacklist'
  set_fact:
    not_fully_disabled: "{{ not_fully_disabled + [\" - Kernel module: '\" ~ mod_name ~ \"' is not fully disabled (missing blacklist)\"] }}"
  when:
    - mod_name not in mounted_modules
    - modprobe_config.stdout is not search('\\bblacklist\\s+' ~ mod_name ~ '\\b')

- name: Vérifie s’il manque un 'install /bin/false'
  set_fact:
    not_fully_disabled: "{{ not_fully_disabled + [\" - Kernel module: '\" ~ mod_name ~ \"' is not fully disabled (missing install)\"] }}"
  when:
    - mod_name not in mounted_modules
    - modprobe_config.stdout is not search('\\binstall\\s+' ~ mod_name ~ '\\s+(/usr)?/bin/(false|true)\\b')

- name: Vérifie si le module est chargé
  shell: lsmod | grep -w {{ mod_name }}
  register: mod_loaded_check
  ignore_errors: true
  changed_when: false
  when: mod_name not in mounted_modules

- name: Ajouter note si le module est chargé
  set_fact:
    not_fully_disabled: "{{ not_fully_disabled + [\" - Kernel module: '\" ~ mod_name ~ \"' is loaded\"] }}"
  when:
    - mod_name not in mounted_modules
    - mod_loaded_check.rc == 0
