- name: Lire les directives modprobe install/blacklist
  shell: modprobe --showconfig | grep -P '^\s*(blacklist|install)'
  register: modprobe_config
  changed_when: false

- name: Inclure la logique de vérification
  include_tasks: rapport.yml

- name: Afficher les modules ignorés
  when: skipped_modules | length > 0
  debug:
    msg:
      - " -- INFO --"
      - "The following were intentionally skipped:"
      - "{{ skipped_modules }}"

- name: Afficher le résultat final
  debug:
    msg: >-
      {% if not_fully_disabled | length == 0 %}
        ✅ Aucun module noyau inutilisé n'est activé.
        {{ warnings }}
        {{ skipped_modules }}
      {% else %}
        ❌ Modules non complètement désactivés :
        {{ not_fully_disabled }}
        {{ warnings }}
        {{ skipped_modules }}
      {% endif %}
