- name: Vérifie si le module {{ mod_name }} est chargé
  shell: lsmod | grep -w {{ mod_name }}
  register: mod_loaded
  changed_when: false
  failed_when: false

- name: Vérifie la directive 'install' dans modprobe
  shell: modprobe --showconfig | grep -P '\binstall\s+{{ mod_name }}\s+(\/usr)?\/bin\/(true|false)\b'
  register: install_check
  failed_when: false
  changed_when: false

- name: Vérifie si le module est blacklisté
  shell: modprobe --showconfig | grep -P '\bblacklist\s+{{ mod_name }}\b'
  register: blacklist_check
  failed_when: false
  changed_when: false


- name: Déterminer si une remédiation est nécessaire
  set_fact:
    audit_messages: "{{ audit_messages + [ (
      '✅ Le module ' ~ mod_name ~ ' est conforme : non chargé, non chargeable et blacklisté.'
      if (mod_loaded.rc != 0 and install_check.rc == 0 and blacklist_check.rc == 0)
      else '❌ Le module ' ~ mod_name ~ ' est chargé ou mal configuré.'
    ) ] }}"
    audit_fix_modules: >-
      {{ audit_fix_modules + ([ mod_name ] if (mod_loaded.rc == 0 or install_check.rc != 0 or blacklist_check.rc != 0) else []) }}
