- name: Décharger le module {{ mod_name }} s’il est chargé
  shell: |
    modprobe -r {{ mod_name }} 2>/dev/null || true
    rmmod {{ mod_name }} 2>/dev/null || true
  ignore_errors: true

- name: Ajouter la directive 'install /bin/false' si absente
  lineinfile:
    path: "{{ mod_conf_file }}"
    line: "install {{ mod_name }} {{ '/bin/false' | realpath }}"
    create: true
  when: install_check.rc != 0

- name: Ajouter une ligne de blacklist si absente
  lineinfile:
    path: "{{ mod_conf_file }}"
    line: "blacklist {{ mod_name }}"
    create: true
  when: blacklist_check.rc != 0

- name: Afficher le résultat de la remédiation
  debug:
    msg: "🛡️ Le module {{ mod_name }} a été déchargé, rendu non chargeable et blacklisté."
