- name: Boucler sur les modules
  include_tasks: "{{ role_path }}/tasks/audit.yml"
  loop: "{{ Filesystem_List }}"
  loop_control:
    loop_var: mod_name

- name: Appliquer les remédiations pour les modules non conformes
  include_tasks: "{{ role_path }}/tasks/fix.yml"
  loop: "{{ audit_fix_modules }}"
  loop_control:
    loop_var: mod_name
  when:
    Filesystem_Fix_On | default(false)

- name: Résumé de l’audit
  debug:
    var: audit_messages

- name: Résumé des remédiations appliquées
  debug:
    var: audit_fix_messages
