#- name: Initialiser la liste des messages
#  set_fact:

##### A MODIFIER AU BESOIN #####

 #   Filesystem_List:
 #     - cramfs      # CIS 1.1.1.1
 #     - freevxfs    # CIS 1.1.1.2
 #     - hfs         # CIS 1.1.1.3
 #     - hfsplus     # CIS 1.1.1.4
 #     - jffs2       # CIS 1.1.1.5
 #     - overlayfs   # CIS 1.1.1.6
 #     - squashfs    # CIS 1.1.1.7
 #     - udf         # CIS 1.1.1.8
 #     - usb-storage # CIS 1.1.1.9
      # CIS 1.1.1.10 (Selon besoins)
      #- afs #CVE-2022-37402
      #- ceph #CVE-2022-0670
      #- cifs #CVE-2022-29869
      #- exfat #CVE-2022-29973
      #- fat #CVE-2022-22043
      #- fscache #CVE-2022-3630
      #- fuse #CVE-2023-0386
      #- gfs2 #CVE-2023-3212

############ FIN ##############


  #  audit_messages: []      # Messages d'audit
  #  audit_fix_messages: []  # Messages de la remédiation
  #  audit_fix_modules: []   # Les modules a corriger

- name: Boucler sur les modules
  include_tasks: "{{ role_path }}/tasks/audit.yml"
  loop: "{{ Filesystem_List }}"
  loop_control:
    loop_var: mod_name

- name: Appliquer les remédiations pour les modules non conformes
  include_tasks: "{{ role_path }}/tasks/fix.yml"
  loop: "{{ audit_fix_modules }}"
  loop_control:
    loop_var: mod_name

- name: Résumé de l’audit
  debug:
    var: audit_messages

- name: Résumé des remédiations appliquées
  debug:
    var: audit_fix_messages
