- name: Charger les modules filesystem disponibles
  shell: |
    find "$(readlink -f /lib/modules/$(uname -r)/kernel/fs)" -mindepth 1 -maxdepth 1 -type d ! -empty -exec basename {} \;
  register: available_modules_raw
  changed_when: false

- name: Définir la liste des modules disponibles
  set_fact:
    available_modules: "{{ available_modules_raw.stdout_lines }}"

- name: Définir les modules ignorés et ceux avec CVE
  set_fact:
    ignore_modules: ["xfs", "vfat", "ext2", "ext3", "ext4"]
    cve_modules: ["afs", "ceph", "cifs", "exfat", "fat", "fscache", "fuse", "gfs2"]
    warnings: []
    not_fully_disabled: []
    skipped_modules: []

- name: Obtenir les points de montage actifs
  shell: findmnt -knD | awk '{print $2}' | sort -u
  register: mounted_paths
  changed_when: false

- name: Extraire les modules montés
  set_fact:
    mounted_modules: "{{ mounted_paths.stdout_lines | map('basename') | list }}"

- name: Vérifier chaque module individuellement
  include_tasks: check_module.yml
  loop: "{{ available_modules }}"
  loop_control:
    loop_var: mod_name
