---
- name: Audit des file system actif ( CIS 1.1.1  )
  hosts: all
  become: true

  tasks:
    - name: Appliquer le rôle Filesystem_Kernel_Module pour chaque module
      #when: Filesystem_Kernel_Modules_On
      include_role:
        name: Filesystem_Kernel_Modules
