#partition_config:
#  - path: /tmp
#    systemd_unit: tmp.mount
#    required_mount_options: ["rw", "nosuid", "nodev"]
#  - path: /home
#    systemd_unit: home.mount
#    required_mount_options: ["rw", "nodev"]
